// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/memory.proto

package memosv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemoryType int32

const (
	MemoryType_MEMORY_TYPE_UNSPECIFIED MemoryType = 0
	MemoryType_MEMORY_TYPE_EPISODIC    MemoryType = 1
	MemoryType_MEMORY_TYPE_SEMANTIC    MemoryType = 2
	MemoryType_MEMORY_TYPE_PROCEDURAL  MemoryType = 3
	MemoryType_MEMORY_TYPE_REFLECTIVE  MemoryType = 4
	MemoryType_MEMORY_TYPE_TRANSIENT   MemoryType = 5
)

// Enum value maps for MemoryType.
var (
	MemoryType_name = map[int32]string{
		0: "MEMORY_TYPE_UNSPECIFIED",
		1: "MEMORY_TYPE_EPISODIC",
		2: "MEMORY_TYPE_SEMANTIC",
		3: "MEMORY_TYPE_PROCEDURAL",
		4: "MEMORY_TYPE_REFLECTIVE",
		5: "MEMORY_TYPE_TRANSIENT",
	}
	MemoryType_value = map[string]int32{
		"MEMORY_TYPE_UNSPECIFIED": 0,
		"MEMORY_TYPE_EPISODIC":    1,
		"MEMORY_TYPE_SEMANTIC":    2,
		"MEMORY_TYPE_PROCEDURAL":  3,
		"MEMORY_TYPE_REFLECTIVE":  4,
		"MEMORY_TYPE_TRANSIENT":   5,
	}
)

func (x MemoryType) Enum() *MemoryType {
	p := new(MemoryType)
	*p = x
	return p
}

func (x MemoryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemoryType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_memory_proto_enumTypes[0].Descriptor()
}

func (MemoryType) Type() protoreflect.EnumType {
	return &file_proto_memory_proto_enumTypes[0]
}

func (x MemoryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemoryType.Descriptor instead.
func (MemoryType) EnumDescriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{0}
}

type Memory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Type          MemoryType             `protobuf:"varint,4,opt,name=type,proto3,enum=memos.v1.MemoryType" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,6,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Importance    float32                `protobuf:"fixed32,7,opt,name=importance,proto3" json:"importance,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Memory) Reset() {
	*x = Memory{}
	mi := &file_proto_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Memory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memory) ProtoMessage() {}

func (x *Memory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memory.ProtoReflect.Descriptor instead.
func (*Memory) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{0}
}

func (x *Memory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Memory) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Memory) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Memory) GetType() MemoryType {
	if x != nil {
		return x.Type
	}
	return MemoryType_MEMORY_TYPE_UNSPECIFIED
}

func (x *Memory) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Memory) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *Memory) GetImportance() float32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *Memory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Memory) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Memory) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Type          MemoryType             `protobuf:"varint,3,opt,name=type,proto3,enum=memos.v1.MemoryType" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Importance    float32                `protobuf:"fixed32,5,opt,name=importance,proto3" json:"importance,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_proto_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{1}
}

func (x *StoreRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *StoreRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StoreRequest) GetType() MemoryType {
	if x != nil {
		return x.Type
	}
	return MemoryType_MEMORY_TYPE_UNSPECIFIED
}

func (x *StoreRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StoreRequest) GetImportance() float32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *StoreRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_proto_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{2}
}

func (x *StoreResponse) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *StoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RetrieveRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TenantId            string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AgentId             string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Query               string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Limit               int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	SimilarityThreshold float32                `protobuf:"fixed32,5,opt,name=similarity_threshold,json=similarityThreshold,proto3" json:"similarity_threshold,omitempty"`
	// Weighting factors for ranking
	AlphaSemantic   float32 `protobuf:"fixed32,6,opt,name=alpha_semantic,json=alphaSemantic,proto3" json:"alpha_semantic,omitempty"`
	BetaTemporal    float32 `protobuf:"fixed32,7,opt,name=beta_temporal,json=betaTemporal,proto3" json:"beta_temporal,omitempty"`
	GammaImportance float32 `protobuf:"fixed32,8,opt,name=gamma_importance,json=gammaImportance,proto3" json:"gamma_importance,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RetrieveRequest) Reset() {
	*x = RetrieveRequest{}
	mi := &file_proto_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRequest) ProtoMessage() {}

func (x *RetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{3}
}

func (x *RetrieveRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RetrieveRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RetrieveRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RetrieveRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RetrieveRequest) GetSimilarityThreshold() float32 {
	if x != nil {
		return x.SimilarityThreshold
	}
	return 0
}

func (x *RetrieveRequest) GetAlphaSemantic() float32 {
	if x != nil {
		return x.AlphaSemantic
	}
	return 0
}

func (x *RetrieveRequest) GetBetaTemporal() float32 {
	if x != nil {
		return x.BetaTemporal
	}
	return 0
}

func (x *RetrieveRequest) GetGammaImportance() float32 {
	if x != nil {
		return x.GammaImportance
	}
	return 0
}

type RetrieveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memories      []*ScoredMemory        `protobuf:"bytes,1,rep,name=memories,proto3" json:"memories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResponse) Reset() {
	*x = RetrieveResponse{}
	mi := &file_proto_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResponse) ProtoMessage() {}

func (x *RetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResponse.ProtoReflect.Descriptor instead.
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{4}
}

func (x *RetrieveResponse) GetMemories() []*ScoredMemory {
	if x != nil {
		return x.Memories
	}
	return nil
}

type ScoreBreakdown struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SemanticScore      float32                `protobuf:"fixed32,1,opt,name=semantic_score,json=semanticScore,proto3" json:"semantic_score,omitempty"`                // Semantic similarity percentage
	TemporalScore      float32                `protobuf:"fixed32,2,opt,name=temporal_score,json=temporalScore,proto3" json:"temporal_score,omitempty"`                // Temporal decay / recency percentage
	ImportanceScore    float32                `protobuf:"fixed32,3,opt,name=importance_score,json=importanceScore,proto3" json:"importance_score,omitempty"`          // Importance percentage
	ReinforcementScore float32                `protobuf:"fixed32,4,opt,name=reinforcement_score,json=reinforcementScore,proto3" json:"reinforcement_score,omitempty"` // Reinforcement / retrieval bonus percentage
	Layer              string                 `protobuf:"bytes,5,opt,name=layer,proto3" json:"layer,omitempty"`                                                       // Memory layer (working, episodic, long_term, archive)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ScoreBreakdown) Reset() {
	*x = ScoreBreakdown{}
	mi := &file_proto_memory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreBreakdown) ProtoMessage() {}

func (x *ScoreBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreBreakdown.ProtoReflect.Descriptor instead.
func (*ScoreBreakdown) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{5}
}

func (x *ScoreBreakdown) GetSemanticScore() float32 {
	if x != nil {
		return x.SemanticScore
	}
	return 0
}

func (x *ScoreBreakdown) GetTemporalScore() float32 {
	if x != nil {
		return x.TemporalScore
	}
	return 0
}

func (x *ScoreBreakdown) GetImportanceScore() float32 {
	if x != nil {
		return x.ImportanceScore
	}
	return 0
}

func (x *ScoreBreakdown) GetReinforcementScore() float32 {
	if x != nil {
		return x.ReinforcementScore
	}
	return 0
}

func (x *ScoreBreakdown) GetLayer() string {
	if x != nil {
		return x.Layer
	}
	return ""
}

type ScoredMemory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memory        *Memory                `protobuf:"bytes,1,opt,name=memory,proto3" json:"memory,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	Breakdown     *ScoreBreakdown        `protobuf:"bytes,3,opt,name=breakdown,proto3" json:"breakdown,omitempty"` // Phase 4: Explainability breakdown
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoredMemory) Reset() {
	*x = ScoredMemory{}
	mi := &file_proto_memory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoredMemory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoredMemory) ProtoMessage() {}

func (x *ScoredMemory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoredMemory.ProtoReflect.Descriptor instead.
func (*ScoredMemory) Descriptor() ([]byte, []int) {
	return file_proto_memory_proto_rawDescGZIP(), []int{6}
}

func (x *ScoredMemory) GetMemory() *Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *ScoredMemory) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScoredMemory) GetBreakdown() *ScoreBreakdown {
	if x != nil {
		return x.Breakdown
	}
	return nil
}

var File_proto_memory_proto protoreflect.FileDescriptor

const file_proto_memory_proto_rawDesc = "" +
	"\n" +
	"\x12proto/memory.proto\x12\bmemos.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xfd\x02\n" +
	"\x06Memory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12(\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.memos.v1.MemoryTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1c\n" +
	"\tembedding\x18\x06 \x03(\x02R\tembedding\x12\x1e\n" +
	"\n" +
	"importance\x18\a \x01(\x02R\n" +
	"importance\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x123\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xdf\x01\n" +
	"\fStoreRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12(\n" +
	"\x04type\x18\x03 \x01(\x0e2\x14.memos.v1.MemoryTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"importance\x18\x05 \x01(\x02R\n" +
	"importance\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"F\n" +
	"\rStoreResponse\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x9f\x02\n" +
	"\x0fRetrieveRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x121\n" +
	"\x14similarity_threshold\x18\x05 \x01(\x02R\x13similarityThreshold\x12%\n" +
	"\x0ealpha_semantic\x18\x06 \x01(\x02R\ralphaSemantic\x12#\n" +
	"\rbeta_temporal\x18\a \x01(\x02R\fbetaTemporal\x12)\n" +
	"\x10gamma_importance\x18\b \x01(\x02R\x0fgammaImportance\"F\n" +
	"\x10RetrieveResponse\x122\n" +
	"\bmemories\x18\x01 \x03(\v2\x16.memos.v1.ScoredMemoryR\bmemories\"\xd0\x01\n" +
	"\x0eScoreBreakdown\x12%\n" +
	"\x0esemantic_score\x18\x01 \x01(\x02R\rsemanticScore\x12%\n" +
	"\x0etemporal_score\x18\x02 \x01(\x02R\rtemporalScore\x12)\n" +
	"\x10importance_score\x18\x03 \x01(\x02R\x0fimportanceScore\x12/\n" +
	"\x13reinforcement_score\x18\x04 \x01(\x02R\x12reinforcementScore\x12\x14\n" +
	"\x05layer\x18\x05 \x01(\tR\x05layer\"\x86\x01\n" +
	"\fScoredMemory\x12(\n" +
	"\x06memory\x18\x01 \x01(\v2\x10.memos.v1.MemoryR\x06memory\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x126\n" +
	"\tbreakdown\x18\x03 \x01(\v2\x18.memos.v1.ScoreBreakdownR\tbreakdown*\xb0\x01\n" +
	"\n" +
	"MemoryType\x12\x1b\n" +
	"\x17MEMORY_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14MEMORY_TYPE_EPISODIC\x10\x01\x12\x18\n" +
	"\x14MEMORY_TYPE_SEMANTIC\x10\x02\x12\x1a\n" +
	"\x16MEMORY_TYPE_PROCEDURAL\x10\x03\x12\x1a\n" +
	"\x16MEMORY_TYPE_REFLECTIVE\x10\x04\x12\x19\n" +
	"\x15MEMORY_TYPE_TRANSIENT\x10\x052\x8c\x01\n" +
	"\rMemoryService\x128\n" +
	"\x05Store\x12\x16.memos.v1.StoreRequest\x1a\x17.memos.v1.StoreResponse\x12A\n" +
	"\bRetrieve\x12\x19.memos.v1.RetrieveRequest\x1a\x1a.memos.v1.RetrieveResponseB)Z'github.com/mohi1038/memos/proto/memosv1b\x06proto3"

var (
	file_proto_memory_proto_rawDescOnce sync.Once
	file_proto_memory_proto_rawDescData []byte
)

func file_proto_memory_proto_rawDescGZIP() []byte {
	file_proto_memory_proto_rawDescOnce.Do(func() {
		file_proto_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_memory_proto_rawDesc), len(file_proto_memory_proto_rawDesc)))
	})
	return file_proto_memory_proto_rawDescData
}

var file_proto_memory_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_memory_proto_goTypes = []any{
	(MemoryType)(0),               // 0: memos.v1.MemoryType
	(*Memory)(nil),                // 1: memos.v1.Memory
	(*StoreRequest)(nil),          // 2: memos.v1.StoreRequest
	(*StoreResponse)(nil),         // 3: memos.v1.StoreResponse
	(*RetrieveRequest)(nil),       // 4: memos.v1.RetrieveRequest
	(*RetrieveResponse)(nil),      // 5: memos.v1.RetrieveResponse
	(*ScoreBreakdown)(nil),        // 6: memos.v1.ScoreBreakdown
	(*ScoredMemory)(nil),          // 7: memos.v1.ScoredMemory
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 9: google.protobuf.Struct
}
var file_proto_memory_proto_depIdxs = []int32{
	0,  // 0: memos.v1.Memory.type:type_name -> memos.v1.MemoryType
	8,  // 1: memos.v1.Memory.created_at:type_name -> google.protobuf.Timestamp
	8,  // 2: memos.v1.Memory.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 3: memos.v1.Memory.metadata:type_name -> google.protobuf.Struct
	0,  // 4: memos.v1.StoreRequest.type:type_name -> memos.v1.MemoryType
	9,  // 5: memos.v1.StoreRequest.metadata:type_name -> google.protobuf.Struct
	7,  // 6: memos.v1.RetrieveResponse.memories:type_name -> memos.v1.ScoredMemory
	1,  // 7: memos.v1.ScoredMemory.memory:type_name -> memos.v1.Memory
	6,  // 8: memos.v1.ScoredMemory.breakdown:type_name -> memos.v1.ScoreBreakdown
	2,  // 9: memos.v1.MemoryService.Store:input_type -> memos.v1.StoreRequest
	4,  // 10: memos.v1.MemoryService.Retrieve:input_type -> memos.v1.RetrieveRequest
	3,  // 11: memos.v1.MemoryService.Store:output_type -> memos.v1.StoreResponse
	5,  // 12: memos.v1.MemoryService.Retrieve:output_type -> memos.v1.RetrieveResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_memory_proto_init() }
func file_proto_memory_proto_init() {
	if File_proto_memory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_memory_proto_rawDesc), len(file_proto_memory_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_memory_proto_goTypes,
		DependencyIndexes: file_proto_memory_proto_depIdxs,
		EnumInfos:         file_proto_memory_proto_enumTypes,
		MessageInfos:      file_proto_memory_proto_msgTypes,
	}.Build()
	File_proto_memory_proto = out.File
	file_proto_memory_proto_goTypes = nil
	file_proto_memory_proto_depIdxs = nil
}
